### PR TITLE
Cleanup Code Base

### PR DESCRIPTION
**Pull request by zifix**
Walked through the code and inlined functions and reformatted the files. Also threw out node_modules and updated the dependencies. Lemme know what you think.

Further ideas:
* Use promises instead of sync methods. This way we can do central error handling directly in express.
* Maybe turn chapter and the scrapers into classes?
* Ideally we could run the reader as a single-page application and throw out or at least separate nunjucks in the backend from the api :) That way we could later easier support apps.

### CODE REVIEW

**Comment by zifix** [comment]
PS: How can we test the changes? What URL do you use and do you have a way to check the stuff that's downloaded for correctness?

**Comment by cademcniven** [comment]
I use https://ncode.syosetu.com/n0809hm/ since it only has a couple chapters (no need to download 800 just to test something). I mostly just check that the novel information page (description, chapter list, etc) is correct, all chapters were downloaded, and that the chapters themselves don't look totally mangled

**Comment by zifix** [comment]
```
The Server is running at: http://localhost:3069/
Attempting to download novel from https://ncode.syosetu.com/n0809hm/
Downloading metadata for 【完結】醜いと言われて婚約破棄された伯爵令嬢です。
Downloading chapter 1/6 of 【完結】醜いと言われて婚約破棄された伯爵令嬢です。
Downloading chapter 2/6 of 【完結】醜いと言われて婚約破棄された伯爵令嬢です。
Downloading chapter 3/6 of 【完結】醜いと言われて婚約破棄された伯爵令嬢です。
Downloading chapter 4/6 of 【完結】醜いと言われて婚約破棄された伯爵令嬢です。
Downloading chapter 5/6 of 【完結】醜いと言われて婚約破棄された伯爵令嬢です。
Downloading chapter 6/6 of 【完結】醜いと言われて婚約破棄された伯爵令嬢です。
Updating metadata for 【完結】醜いと言われて婚約破棄された伯爵令嬢です。
```
Works fine for me.

**Comment by zifix** [comment]
Optimized two more places. Also found a bug: GetAllNovels is called before ./novels/ is created. Also the folder is used in two places. Should probably be an export of fileLogic imho.

**Pull request merged**
